### ISSUE TITLE
access to the dataset 

### ISSUE THREAD

**Issue by yazeed42** [maweihong/BClayinghens#1]
hey i think the website you have upload the data to is strictly for Chinese users because it required a Chinese phone number so could you guid us to a way to access the data from outside china.

**Comment by maweihong** [comment]
Hi

    I am finding a way to solve this issue.




Best regards
















At 2024-11-27 00:06:19, "yazeed42" ***@***.***> wrote:

hey i think the website you have upload the data to is strictly for Chinese users because it required a Chinese phone number so could you guid us to a way to access the data from outside china.

**Comment by yazeed42** [comment]
Thanks, I'm excited to hear from you soon.

**Comment by maweihong** [comment]
Hi

user name：opendataset     or  15010958623




Password：opendataset123

15010958623 is the phone number

But it may need User verification code，which is not convenient. You can have a try. if I saw the User verification code of my phone, I will send you the code via email.

Best wished




Weihong Ma



















At 2024-12-01 18:30:03, "yazeed42" ***@***.***> wrote:

Thanks, I'm excited to hear from you soon.

**Comment by yazeed42** [comment]
Could you send me an email on yazeed_42@live.com.

Best regards

**Comment by Lucasmogsan** [comment]
@maweihong do you have a solution to this, I would very much like access to the dataset as well. Thanks in advance,
